name: "CI"

on:
  pull_request:
    branches: [main]

# Allow one run of this workflow per branch and cancel existing runs if triggered again
concurrency:
  group: JustShowMeTheDamnRecipes-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ./source/src
      - run: npm run build
        working-directory: ./source/src
